// Auto-generated by samemind (tools/lib/hooks.mjs buildHooks/installHooks). Safe to regenerate —
// re-running `samemind hooks install --agent opencode` overwrites this whole file.
//
// Best-effort lifecycle-hook approximation for opencode: there is no declarative
// SessionStart/SessionEnd hook (yet) — see github.com/sst/opencode/issues/5409. This plugin's
// `event` hook reacts to the closest available signals instead:
//   session.created — fires on the first real interaction of a NEW session (misses `--continue`
//                      / `--resume` / `/resume` — no bus event fires for those, per the issue).
//   session.idle     — fires whenever the session goes idle (per turn), not once at true session
//                      end; used here as the best available "persist" checkpoint.
// Same two actions samemind wires for Claude Code / Codex (see hook-templates/session-*.json):
// handoff on start, an inbox stub note on idle. Fire-and-forget child process — never blocks
// opencode's own turn.
import { exec } from 'node:child_process';

function run(cmd) {
  exec(cmd, { env: { ...process.env, OKF_ROOT: '${ROOT}' } }, () => {});
}

export const SamemindHooks = async () => ({
  event: async ({ event }) => {
    if (event.type === 'session.created') {
      run('${CLI} handoff');
    }
    if (event.type === 'session.idle') {
      run('sh -c \'mkdir -p "$OKF_ROOT/inbox"; printf "\\n## %s - session end (${ENGINE})\\n\\nAuto stub from samemind session.idle hook - fill Done/Decided/Next before it is lost.\\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$OKF_ROOT/inbox/${ENGINE}.md"\'');
    }
  },
});
